name = "Cold War"
description = ""
start_date = "1949.1.1"

[[great_powers]]
code = "GBR"
description = ""

[[great_powers]]
code = "CHN"
description = ""

[[great_powers]]
code = "FRA"
description = ""

[[great_powers]]
code = "SOV"
description = ""

[[great_powers]]
code = "USA"
description = ""